import Head from "next/head";
import Banner from "~/components/Banner";
import Nav from "~/components/Nav";
import Section from "~/components/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>EVNT - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section>
        <Nav />
        <Banner />
      </Section>
    </>
  );
}
