import Head from "next/head";
import Banner from "~/components/Banner";
import Nav from "~/components/Nav";
import Section from "~/components/Section";

export default function Home() {
  return (
    <>
      <Head>
        <title>EVNT - Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Section className="h-screen">
        <Nav />
        <Banner />
      </Section>
      <Section className="mb-16 rounded-b-3xl bg-slate-800">
        <h2 className="flex justify-between p-20 font-primary text-6xl leading-snug text-white">
          <span>Join.</span> <span>Host.</span> <span>Stream.</span>{" "}
          <span>Attend.</span> <span>Enjoy.</span>
        </h2>
      </Section>
      <Section className="mb-40">
        <div className="grid grid-cols-12 gap-16">
          <div className="col-span-3 h-[300px] rounded-3xl bg-slate-800"></div>
          <div className="col-span-4 h-[300px] rounded-3xl bg-slate-800"></div>
          <div className="col-span-5 h-[300px] rounded-3xl bg-slate-800"></div>
          <div className="col-span-6 h-[300px] rounded-3xl bg-slate-800"></div>
          <div className="col-span-6 h-[300px] rounded-3xl bg-slate-800"></div>
        </div>
      </Section>
    </>
  );
}
